### ISSUE TITLE
Support channel groups

### ISSUE THREAD

**Issue by xiaobuxun** [pubnub/eon#11]
I can not find how subscribe channel group use eon

**Comment by nare06** [comment]
Any updates?? I would like to know too...

**Comment by ianjennings** [comment]
Channel groups are not supported at the moment.

**Comment by ianjennings** [comment]
https://github.com/pubnub/eon-chart/issues/5

**Comment by ianjennings** [comment]
Channel groups are now supported in ```1.0.0```. 
https://github.com/pubnub/eon-chart
