### ISSUE TITLE
Redirect loop on web

### ISSUE THREAD

**Issue by rborn** [pubnub/eon#6]
The big_orange_top_left_button `Project EON` leads to a redirect loop :smile:

**Comment by stephenlb** [comment]
WHATs that now I get a pretty good working situation on my clicks.

> `curl -si http://www.pubnub.com/developers/eon/ | head`

```shell
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 14905
Accept-Ranges: bytes
Date: Tue, 02 Jun 2015 22:45:49 GMT
Age: 6
Connection: keep-alive
Vary: Accept-Encoding
```

**Comment by rborn** [comment]
@stephenlb Now it's ok, before was linking to http://www.pubnub.com//developers/eon/index.html

**Comment by stephenlb** [comment]
👍
