### ISSUE TITLE
Is it possible for custom html marker popups or onclick listeners for marker popups?

### ISSUE THREAD

**Issue by techscientist** [pubnub/eon#9]
Hi,

This project is awesome, and I'm currently using this eon map framework to build a realtime dispatch system. The web app uses angularjs. So I was wondering if it was possible for a maker popup to have custom html instead of just text. Or, is there an onclick listener for marker popups? I need to show relative information when the person clicks on a popup.

Thanks for helping

**Comment by ianjennings** [comment]
Checkout the MapBox documentation here:
https://www.mapbox.com/mapbox.js/example/v1.0.0/clicks-in-popups/
